{% args F, doc_list, relpath, extra %}
<!-- This file is auto-generated by papersman, https://github.com/pfalcon/papersman -->
<html>
<head>
<link rel="stylesheet" type="text/css" href="{{relpath}}/index/style.css">
<link rel="stylesheet" type="text/css" href="{{relpath}}/index/tags.css">
</head>
<body>

{% if "header" in extra %}
<h1>{{ extra["header"] }}</h1>
{% endif %}

{% if "tagmap" in extra %}
<div class="tags-index">
{% for t, docs in sorted(extra["tagmap"].items()) %}
<a class="tag {{ F.tag2classes(t) }}" href="{{relpath}}/{{ F.tag2url(t) }}">{{ t }}&nbsp;({{ len(docs) }})</a><br/>
{% endfor %}
</div>
{% endif %}

{% for d in doc_list %}
<a name="{{ d["md5"] }}" />
<p><a href="{{relpath}}/{{ d["path"] }}">{{ d["name"] }}</a><br/>
{% for t in d["tags"] %}
<a class="tag {{ F.tag2classes(t) }}" href="{{relpath}}/{{ F.tag2url(t) }}">{{ t }}</a>
{% endfor %}

{% if "cites" in d %}
<p class="annot">Cites:
<ul class="annot">
{% for citeid in d["cites"] %}
<li><a href="{{relpath}}/index.html#{{ extra["idmap"][citeid]["md5"] }}">{{ extra["idmap"][citeid]["name"] }}</a>
{% endfor %}
</ul>
</p>
{% endif %}

{% if "notes" in d %}
<p class="annot">Notes:
<ul class="annot">
{% for note in d["notes"] %}
<li>{{ note }}
{% endfor %}
</ul>
</p>
{% endif %}

</p>

{% endfor %}
</body>
</html>
