{% args F, doc_list, relpath, extra %}
<!-- This file is auto-generated by papersman, https://github.com/pfalcon/papersman -->
<html>
<head>
<link rel="stylesheet" type="text/css" href="{{relpath}}/index/style.css">
<link rel="stylesheet" type="text/css" href="{{relpath}}/index/tags.css">
</head>
<body>

{% if "header" in extra %}
<h1>{{ extra["header"] }}</h1>
{% endif %}

{% for d in doc_list %}
<p><a href="{{relpath}}/{{ d["name"] }}">{{ d["name"] }}</a><br/>
{% for t in d["tags"] %}
<a class="tag tag-{{ F.tag2id(t) }}" href="{{relpath}}/{{ F.tag2url(t) }}">{{ t }}</a>
{% endfor %}
</p>

{% endfor %}
</body>
</html>
